import os


os.environ.setdefault("SYNBIO_DAILY_NOW", "2026-06-11T12:00:00+08:00")
os.environ.setdefault("SYNBIO_SKIP_DOTENV", "1")

for key in (
    "ANTHROPIC_BASE_URL",
    "ANTHROPIC_AUTH_TOKEN",
    "ANTHROPIC_MODEL",
    "SMTP_PASSWORD",
    "SYNBIO_DAILY_HOME",
    "SYNBIO_LLM_JUDGE_CACHE",
    "SYNBIO_LLM_ASCII_PROMPTS",
    "SYNBIO_SEARCH_PROVIDER",
    "SYNBIO_SEARCH_FIXTURE",
    "SERPER_API_KEY",
    "BRAVE_SEARCH_API_KEY",
    "BING_SEARCH_API_KEY",
    "TAVILY_API_KEY",
):
    os.environ.pop(key, None)
